name: core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  system_proxy: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
