name: core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  system_proxy: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.8.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
