IMAGE_PATH="assets/images"
SUFFIX_PNG="png"
SUFFIX_SVG="svg"
WRITE_TO="lib/res/image.dart"

{
  echo "/// This file is automatically generated, you should not edit it manually."
  echo "class Images {"
  echo ""
} > "./$WRITE_TO"

for files in "./$IMAGE_PATH"/*."$SUFFIX_PNG"
do
  fileName=$(eval "basename $files *.$SUFFIX_PNG")
  withoutSuffix=$(eval "basename $fileName .$SUFFIX_PNG")
  echo "  static const $withoutSuffix = '$IMAGE_PATH/$fileName';" >> "./$WRITE_TO"
done

{
  echo "}"
} >> "./$WRITE_TO"